package mru.tsc.model;

public class Figure extends Toy{
		
	/**
	 * This class is used to create figure objects, this is useful for adding them to the arraylist, most of the parameters come from the superclass: toy
	 */
	char classification;
	/**
	 * The Constructor creates the object. Several of the parameters come from the toy superclass
	 * @param SN
	 * @param name
	 * @param brand
	 * @param price
	 * @param availableCount
	 * @param ageAppropriate
	 * @param Class
	 */
	public Figure(String SN, String name, String brand, double price, int availableCount, int ageAppropriate, String Class) {
		super(SN, name, brand, price, availableCount, ageAppropriate);
		classification = Class.charAt(0);
		// TODO Auto-generated constructor stub
	}
	// ToString method which allows the Figure to appear in a readable form, generated by Eclipse
	@Override
	public String toString() {
		return "Figure [SN=" + SN + ", name=" + name + ", brand=" + brand + ", price=" + price + ", availableCount="
				+ availableCount + ", ageAppropraite=" + ageAppropraite + ", classification=" + classification + "]";
	}
	// Setters and getters, generated by Eclipse
	public char getClassification() {
		return classification;
	}
	public void setClassification(char classification) {
		this.classification = classification;
	}
	// format which will be called and used when the arraylist is saved into the database
	
public String format() {
		
		return SN + ";" + name + ";" + brand + ";" + price + ";" + availableCount + ";" + ageAppropraite + ";" + classification;
	
	}

}
