package mru.tsc.model;

public class Puzzle extends Toy {

	/**
	 * This class is used to create puzzle objects, useful for adding them to the
	 * arraylist. Most of the parameters come from the superclass: Toy
	 */
	String puzzleType;

	/**
	 * Constructor used to create the puzzle object. Several of the parameters come
	 * from the Toy superclass
	 * 
	 * @param SN
	 * @param name
	 * @param brand
	 * @param price
	 * @param availableCount
	 * @param ageAppropriate
	 * @param type
	 * @param type
	 */
	public Puzzle(String SN, String name, String brand, double price, int availableCount, int ageAppropriate,
			String type) {
		super(SN, name, brand, price, availableCount, ageAppropriate);
		// TODO Auto-generated constructor stub
		puzzleType = type;
	}

	// ToString method which allows the puzzle object to appear in a readable form,
	// generated by Eclipse
	@Override
	public String toString() {
		return "Puzzle [SN=" + SN + ", name=" + name + ", brand=" + brand + ", price=" + price + ", availableCount="
				+ availableCount + ", ageAppropraite=" + ageAppropraite + ", puzzleType=" + puzzleType + "]";
	}

	// Getters and setters, Generated by Eclipse
	public String getPuzzleType() {
		return puzzleType;
	}

	public void setPuzzleType(String puzzleType) {
		this.puzzleType = puzzleType;
	}
	
	// format which will be called and used when the arraylist is saved into the database
	
public String format() {
		
		return SN + ";" + name + ";" + brand + ";" + price + ";" + availableCount + ";" + ageAppropraite + ";" + puzzleType;
	
	}

}
