package mru.tsc.model;

public class BoardGame extends Toy{

	/**
	 * 
	 * This class is used to create BoardGame objects, this is useful for adding them to the arraylist. It inherits a lot of parameters from its super class: Toy
	 */
	 
	String players;
	String designers;
	
	/**
	 * the Constructor used to create the board game objects based on the parameters passed into it. Many of the parameters come from the toy superclass
	 * @param SN
	 * @param name
	 * @param brand
	 * @param price
	 * @param availableCount
	 * @param ageAppropriate
	 * @param player
	 * @param designer
	 */
	public BoardGame(String SN, String name, String brand, double price, int availableCount, int ageAppropriate, String player, String designer) {
		super(SN, name, brand, price, availableCount, ageAppropriate);
		players = player;
		designers = designer;
		
	}
	
	// Getters and setters generated by Eclipse
	public String getDesigners() {
		return designers;
	}

	public void setDesigners(String designers) {
		this.designers = designers;
	}

	// ToString method which allows the Board Game to appear in a readable form, generated by Eclipse
	@Override
	public String toString() {
		return "BoardGame [SN=" + SN + ", name=" + name + ", brand=" + brand + ", price=" + price + ", availableCount="
				+ availableCount + ", ageAppropraite=" + ageAppropraite + ", players=" + players + ", designers="
				+ designers + "]";
	
}
	// format which will be called and used when the arraylist is saved into the database
public String format() {
		
		return SN + ";" + name + ";" + brand + ";" + price + ";" + availableCount + ";" + ageAppropraite + ";" + players + ";" + designers;
	
	}
}