package mru.tsc.model;

public abstract class Toy {
	/**
	 * Abstract class which provides a constructor as well as getters and setters
	 * for the parameters that the four Toy types share this is a superclass for all
	 * the toy types and allows for easier initialization
	 */
	String SN;
	String name;
	String brand;
	String type;
	double price;
	int availableCount;
	int ageAppropraite;

	/**
	 * Contructor for the parameters that all of the variables that are shared
	 * between the four toy types
	 * 
	 * @param SN
	 * @param name
	 * @param brand
	 * @param price
	 * @param availableCount
	 * @param ageAppropriate
	 */
	public Toy(String SN, String name, String brand, double price, int availableCount, int ageAppropriate) {
		this.SN = SN;
		this.name = name;
		this.brand = brand;
		this.price = price;
		this.availableCount = availableCount;
		this.ageAppropraite = ageAppropriate;
	}

	// getters and setters, generated by Eclipse
	public String getSN() {
		return SN;
	}

	public void setSN(String sN) {
		SN = sN;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getAvailableCount() {
		return availableCount;
	}

	public void setAvailableCount(int availableCount) {
		this.availableCount = availableCount;
	}

	public int getAgeAppropraite() {
		return ageAppropraite;
	}

	public void setAgeAppropraite(int ageAppropraite) {
		this.ageAppropraite = ageAppropraite;
	}
}
